// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SCENE_LITE_SERIALIZATION_H_
#define FLATBUFFERS_GENERATED_SCENE_LITE_SERIALIZATION_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace lite {
namespace serialization {

struct Vec2;

struct Vec3;

struct Vec4;

struct Mat4;

struct TextureInfoFB;
struct TextureInfoFBBuilder;

struct MaterialFB;
struct MaterialFBBuilder;

struct MPBRLitMaterialFB;
struct MPBRLitMaterialFBBuilder;

struct NodeFB;
struct NodeFBBuilder;

struct MeshNodeFB;
struct MeshNodeFBBuilder;

struct CameraNodeFB;
struct CameraNodeFBBuilder;

struct IblFB;
struct IblFBBuilder;

struct SceneFB;
struct SceneFBBuilder;

enum MaterialKind : uint8_t {
  MaterialKind_NONE = 0,
  MaterialKind_MaterialFB = 1,
  MaterialKind_MPBRLitMaterialFB = 2,
  MaterialKind_MIN = MaterialKind_NONE,
  MaterialKind_MAX = MaterialKind_MPBRLitMaterialFB
};

inline const MaterialKind (&EnumValuesMaterialKind())[3] {
  static const MaterialKind values[] = {
    MaterialKind_NONE,
    MaterialKind_MaterialFB,
    MaterialKind_MPBRLitMaterialFB
  };
  return values;
}

inline const char * const *EnumNamesMaterialKind() {
  static const char * const names[4] = {
    "NONE",
    "MaterialFB",
    "MPBRLitMaterialFB",
    nullptr
  };
  return names;
}

inline const char *EnumNameMaterialKind(MaterialKind e) {
  if (::flatbuffers::IsOutRange(e, MaterialKind_NONE, MaterialKind_MPBRLitMaterialFB)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMaterialKind()[index];
}

template<typename T> struct MaterialKindTraits {
  static const MaterialKind enum_value = MaterialKind_NONE;
};

template<> struct MaterialKindTraits<lite::serialization::MaterialFB> {
  static const MaterialKind enum_value = MaterialKind_MaterialFB;
};

template<> struct MaterialKindTraits<lite::serialization::MPBRLitMaterialFB> {
  static const MaterialKind enum_value = MaterialKind_MPBRLitMaterialFB;
};

template <bool B = false>
bool VerifyMaterialKind(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, MaterialKind type);
template <bool B = false>
bool VerifyMaterialKindVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

enum NodeKind : uint8_t {
  NodeKind_NONE = 0,
  NodeKind_NodeFB = 1,
  NodeKind_MeshNodeFB = 2,
  NodeKind_CameraNodeFB = 3,
  NodeKind_MIN = NodeKind_NONE,
  NodeKind_MAX = NodeKind_CameraNodeFB
};

inline const NodeKind (&EnumValuesNodeKind())[4] {
  static const NodeKind values[] = {
    NodeKind_NONE,
    NodeKind_NodeFB,
    NodeKind_MeshNodeFB,
    NodeKind_CameraNodeFB
  };
  return values;
}

inline const char * const *EnumNamesNodeKind() {
  static const char * const names[5] = {
    "NONE",
    "NodeFB",
    "MeshNodeFB",
    "CameraNodeFB",
    nullptr
  };
  return names;
}

inline const char *EnumNameNodeKind(NodeKind e) {
  if (::flatbuffers::IsOutRange(e, NodeKind_NONE, NodeKind_CameraNodeFB)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesNodeKind()[index];
}

template<typename T> struct NodeKindTraits {
  static const NodeKind enum_value = NodeKind_NONE;
};

template<> struct NodeKindTraits<lite::serialization::NodeFB> {
  static const NodeKind enum_value = NodeKind_NodeFB;
};

template<> struct NodeKindTraits<lite::serialization::MeshNodeFB> {
  static const NodeKind enum_value = NodeKind_MeshNodeFB;
};

template<> struct NodeKindTraits<lite::serialization::CameraNodeFB> {
  static const NodeKind enum_value = NodeKind_CameraNodeFB;
};

template <bool B = false>
bool VerifyNodeKind(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, NodeKind type);
template <bool B = false>
bool VerifyNodeKindVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec2 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;

 public:
  Vec2()
      : x_(0),
        y_(0) {
  }
  Vec2(float _x, float _y)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
};
FLATBUFFERS_STRUCT_END(Vec2, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vec3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vec3(float _x, float _y, float _z)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec4 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;
  float w_;

 public:
  Vec4()
      : x_(0),
        y_(0),
        z_(0),
        w_(0) {
  }
  Vec4(float _x, float _y, float _z, float _w)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)),
        w_(::flatbuffers::EndianScalar(_w)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
  float w() const {
    return ::flatbuffers::EndianScalar(w_);
  }
};
FLATBUFFERS_STRUCT_END(Vec4, 16);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Mat4 FLATBUFFERS_FINAL_CLASS {
 private:
  float m_[16];

 public:
  Mat4()
      : m_() {
  }
  Mat4(::flatbuffers::span<const float, 16> _m) {
    ::flatbuffers::CastToArray(m_).CopyFromSpan(_m);
  }
  const ::flatbuffers::Array<float, 16> *m() const {
    return &::flatbuffers::CastToArray(m_);
  }
};
FLATBUFFERS_STRUCT_END(Mat4, 64);

struct TextureInfoFB FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TextureInfoFBBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PATH = 4,
    VT_SRGB = 6,
    VT_WIDTH = 8,
    VT_HEIGHT = 10,
    VT_CHANNELS = 12
  };
  const ::flatbuffers::String *path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PATH);
  }
  bool srgb() const {
    return GetField<uint8_t>(VT_SRGB, 1) != 0;
  }
  uint32_t width() const {
    return GetField<uint32_t>(VT_WIDTH, 0);
  }
  uint32_t height() const {
    return GetField<uint32_t>(VT_HEIGHT, 0);
  }
  uint32_t channels() const {
    return GetField<uint32_t>(VT_CHANNELS, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PATH) &&
           verifier.VerifyString(path()) &&
           VerifyField<uint8_t>(verifier, VT_SRGB, 1) &&
           VerifyField<uint32_t>(verifier, VT_WIDTH, 4) &&
           VerifyField<uint32_t>(verifier, VT_HEIGHT, 4) &&
           VerifyField<uint32_t>(verifier, VT_CHANNELS, 4) &&
           verifier.EndTable();
  }
};

struct TextureInfoFBBuilder {
  typedef TextureInfoFB Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_path(::flatbuffers::Offset<::flatbuffers::String> path) {
    fbb_.AddOffset(TextureInfoFB::VT_PATH, path);
  }
  void add_srgb(bool srgb) {
    fbb_.AddElement<uint8_t>(TextureInfoFB::VT_SRGB, static_cast<uint8_t>(srgb), 1);
  }
  void add_width(uint32_t width) {
    fbb_.AddElement<uint32_t>(TextureInfoFB::VT_WIDTH, width, 0);
  }
  void add_height(uint32_t height) {
    fbb_.AddElement<uint32_t>(TextureInfoFB::VT_HEIGHT, height, 0);
  }
  void add_channels(uint32_t channels) {
    fbb_.AddElement<uint32_t>(TextureInfoFB::VT_CHANNELS, channels, 0);
  }
  explicit TextureInfoFBBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TextureInfoFB> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TextureInfoFB>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TextureInfoFB> CreateTextureInfoFB(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> path = 0,
    bool srgb = true,
    uint32_t width = 0,
    uint32_t height = 0,
    uint32_t channels = 0) {
  TextureInfoFBBuilder builder_(_fbb);
  builder_.add_channels(channels);
  builder_.add_height(height);
  builder_.add_width(width);
  builder_.add_path(path);
  builder_.add_srgb(srgb);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TextureInfoFB> CreateTextureInfoFBDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *path = nullptr,
    bool srgb = true,
    uint32_t width = 0,
    uint32_t height = 0,
    uint32_t channels = 0) {
  auto path__ = path ? _fbb.CreateString(path) : 0;
  return lite::serialization::CreateTextureInfoFB(
      _fbb,
      path__,
      srgb,
      width,
      height,
      channels);
}

struct MaterialFB FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MaterialFBBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           verifier.EndTable();
  }
};

struct MaterialFBBuilder {
  typedef MaterialFB Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(MaterialFB::VT_NAME, name);
  }
  explicit MaterialFBBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MaterialFB> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MaterialFB>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MaterialFB> CreateMaterialFB(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0) {
  MaterialFBBuilder builder_(_fbb);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MaterialFB> CreateMaterialFBDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return lite::serialization::CreateMaterialFB(
      _fbb,
      name__);
}

struct MPBRLitMaterialFB FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MPBRLitMaterialFBBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BASE = 4,
    VT_BASE_COLOR_FACTOR = 6,
    VT_METALLIC_FACTOR = 8,
    VT_ROUGHNESS_FACTOR = 10,
    VT_EMISSIVE_FACTOR = 12,
    VT_BASE_COLOR_TEXTURE = 14,
    VT_NORMAL_TEXTURE = 16,
    VT_METALLIC_ROUGHNESS_TEXTURE = 18,
    VT_OCCLUSION_TEXTURE = 20,
    VT_EMISSIVE_TEXTURE = 22
  };
  const lite::serialization::MaterialFB *base() const {
    return GetPointer<const lite::serialization::MaterialFB *>(VT_BASE);
  }
  const lite::serialization::Vec4 *base_color_factor() const {
    return GetStruct<const lite::serialization::Vec4 *>(VT_BASE_COLOR_FACTOR);
  }
  float metallic_factor() const {
    return GetField<float>(VT_METALLIC_FACTOR, 0.0f);
  }
  float roughness_factor() const {
    return GetField<float>(VT_ROUGHNESS_FACTOR, 1.0f);
  }
  const lite::serialization::Vec3 *emissive_factor() const {
    return GetStruct<const lite::serialization::Vec3 *>(VT_EMISSIVE_FACTOR);
  }
  const lite::serialization::TextureInfoFB *base_color_texture() const {
    return GetPointer<const lite::serialization::TextureInfoFB *>(VT_BASE_COLOR_TEXTURE);
  }
  const lite::serialization::TextureInfoFB *normal_texture() const {
    return GetPointer<const lite::serialization::TextureInfoFB *>(VT_NORMAL_TEXTURE);
  }
  const lite::serialization::TextureInfoFB *metallic_roughness_texture() const {
    return GetPointer<const lite::serialization::TextureInfoFB *>(VT_METALLIC_ROUGHNESS_TEXTURE);
  }
  const lite::serialization::TextureInfoFB *occlusion_texture() const {
    return GetPointer<const lite::serialization::TextureInfoFB *>(VT_OCCLUSION_TEXTURE);
  }
  const lite::serialization::TextureInfoFB *emissive_texture() const {
    return GetPointer<const lite::serialization::TextureInfoFB *>(VT_EMISSIVE_TEXTURE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_BASE) &&
           verifier.VerifyTable(base()) &&
           VerifyField<lite::serialization::Vec4>(verifier, VT_BASE_COLOR_FACTOR, 4) &&
           VerifyField<float>(verifier, VT_METALLIC_FACTOR, 4) &&
           VerifyField<float>(verifier, VT_ROUGHNESS_FACTOR, 4) &&
           VerifyField<lite::serialization::Vec3>(verifier, VT_EMISSIVE_FACTOR, 4) &&
           VerifyOffset(verifier, VT_BASE_COLOR_TEXTURE) &&
           verifier.VerifyTable(base_color_texture()) &&
           VerifyOffset(verifier, VT_NORMAL_TEXTURE) &&
           verifier.VerifyTable(normal_texture()) &&
           VerifyOffset(verifier, VT_METALLIC_ROUGHNESS_TEXTURE) &&
           verifier.VerifyTable(metallic_roughness_texture()) &&
           VerifyOffset(verifier, VT_OCCLUSION_TEXTURE) &&
           verifier.VerifyTable(occlusion_texture()) &&
           VerifyOffset(verifier, VT_EMISSIVE_TEXTURE) &&
           verifier.VerifyTable(emissive_texture()) &&
           verifier.EndTable();
  }
};

struct MPBRLitMaterialFBBuilder {
  typedef MPBRLitMaterialFB Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_base(::flatbuffers::Offset<lite::serialization::MaterialFB> base) {
    fbb_.AddOffset(MPBRLitMaterialFB::VT_BASE, base);
  }
  void add_base_color_factor(const lite::serialization::Vec4 *base_color_factor) {
    fbb_.AddStruct(MPBRLitMaterialFB::VT_BASE_COLOR_FACTOR, base_color_factor);
  }
  void add_metallic_factor(float metallic_factor) {
    fbb_.AddElement<float>(MPBRLitMaterialFB::VT_METALLIC_FACTOR, metallic_factor, 0.0f);
  }
  void add_roughness_factor(float roughness_factor) {
    fbb_.AddElement<float>(MPBRLitMaterialFB::VT_ROUGHNESS_FACTOR, roughness_factor, 1.0f);
  }
  void add_emissive_factor(const lite::serialization::Vec3 *emissive_factor) {
    fbb_.AddStruct(MPBRLitMaterialFB::VT_EMISSIVE_FACTOR, emissive_factor);
  }
  void add_base_color_texture(::flatbuffers::Offset<lite::serialization::TextureInfoFB> base_color_texture) {
    fbb_.AddOffset(MPBRLitMaterialFB::VT_BASE_COLOR_TEXTURE, base_color_texture);
  }
  void add_normal_texture(::flatbuffers::Offset<lite::serialization::TextureInfoFB> normal_texture) {
    fbb_.AddOffset(MPBRLitMaterialFB::VT_NORMAL_TEXTURE, normal_texture);
  }
  void add_metallic_roughness_texture(::flatbuffers::Offset<lite::serialization::TextureInfoFB> metallic_roughness_texture) {
    fbb_.AddOffset(MPBRLitMaterialFB::VT_METALLIC_ROUGHNESS_TEXTURE, metallic_roughness_texture);
  }
  void add_occlusion_texture(::flatbuffers::Offset<lite::serialization::TextureInfoFB> occlusion_texture) {
    fbb_.AddOffset(MPBRLitMaterialFB::VT_OCCLUSION_TEXTURE, occlusion_texture);
  }
  void add_emissive_texture(::flatbuffers::Offset<lite::serialization::TextureInfoFB> emissive_texture) {
    fbb_.AddOffset(MPBRLitMaterialFB::VT_EMISSIVE_TEXTURE, emissive_texture);
  }
  explicit MPBRLitMaterialFBBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MPBRLitMaterialFB> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MPBRLitMaterialFB>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MPBRLitMaterialFB> CreateMPBRLitMaterialFB(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<lite::serialization::MaterialFB> base = 0,
    const lite::serialization::Vec4 *base_color_factor = nullptr,
    float metallic_factor = 0.0f,
    float roughness_factor = 1.0f,
    const lite::serialization::Vec3 *emissive_factor = nullptr,
    ::flatbuffers::Offset<lite::serialization::TextureInfoFB> base_color_texture = 0,
    ::flatbuffers::Offset<lite::serialization::TextureInfoFB> normal_texture = 0,
    ::flatbuffers::Offset<lite::serialization::TextureInfoFB> metallic_roughness_texture = 0,
    ::flatbuffers::Offset<lite::serialization::TextureInfoFB> occlusion_texture = 0,
    ::flatbuffers::Offset<lite::serialization::TextureInfoFB> emissive_texture = 0) {
  MPBRLitMaterialFBBuilder builder_(_fbb);
  builder_.add_emissive_texture(emissive_texture);
  builder_.add_occlusion_texture(occlusion_texture);
  builder_.add_metallic_roughness_texture(metallic_roughness_texture);
  builder_.add_normal_texture(normal_texture);
  builder_.add_base_color_texture(base_color_texture);
  builder_.add_emissive_factor(emissive_factor);
  builder_.add_roughness_factor(roughness_factor);
  builder_.add_metallic_factor(metallic_factor);
  builder_.add_base_color_factor(base_color_factor);
  builder_.add_base(base);
  return builder_.Finish();
}

struct NodeFB FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef NodeFBBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_NAME = 6,
    VT_LOCAL_TRANSFORM = 8,
    VT_VISIBLE = 10,
    VT_CHILDREN_TYPE = 12,
    VT_CHILDREN = 14
  };
  int32_t id() const {
    return GetField<int32_t>(VT_ID, -1);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const lite::serialization::Mat4 *local_transform() const {
    return GetStruct<const lite::serialization::Mat4 *>(VT_LOCAL_TRANSFORM);
  }
  bool visible() const {
    return GetField<uint8_t>(VT_VISIBLE, 1) != 0;
  }
  const ::flatbuffers::Vector<uint8_t> *children_type() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_CHILDREN_TYPE);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *children() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *>(VT_CHILDREN);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ID, 4) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<lite::serialization::Mat4>(verifier, VT_LOCAL_TRANSFORM, 4) &&
           VerifyField<uint8_t>(verifier, VT_VISIBLE, 1) &&
           VerifyOffset(verifier, VT_CHILDREN_TYPE) &&
           verifier.VerifyVector(children_type()) &&
           VerifyOffset(verifier, VT_CHILDREN) &&
           verifier.VerifyVector(children()) &&
           VerifyNodeKindVector(verifier, children(), children_type()) &&
           verifier.EndTable();
  }
};

struct NodeFBBuilder {
  typedef NodeFB Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(int32_t id) {
    fbb_.AddElement<int32_t>(NodeFB::VT_ID, id, -1);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(NodeFB::VT_NAME, name);
  }
  void add_local_transform(const lite::serialization::Mat4 *local_transform) {
    fbb_.AddStruct(NodeFB::VT_LOCAL_TRANSFORM, local_transform);
  }
  void add_visible(bool visible) {
    fbb_.AddElement<uint8_t>(NodeFB::VT_VISIBLE, static_cast<uint8_t>(visible), 1);
  }
  void add_children_type(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> children_type) {
    fbb_.AddOffset(NodeFB::VT_CHILDREN_TYPE, children_type);
  }
  void add_children(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<void>>> children) {
    fbb_.AddOffset(NodeFB::VT_CHILDREN, children);
  }
  explicit NodeFBBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<NodeFB> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<NodeFB>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<NodeFB> CreateNodeFB(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = -1,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    const lite::serialization::Mat4 *local_transform = nullptr,
    bool visible = true,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> children_type = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<void>>> children = 0) {
  NodeFBBuilder builder_(_fbb);
  builder_.add_children(children);
  builder_.add_children_type(children_type);
  builder_.add_local_transform(local_transform);
  builder_.add_name(name);
  builder_.add_id(id);
  builder_.add_visible(visible);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<NodeFB> CreateNodeFBDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = -1,
    const char *name = nullptr,
    const lite::serialization::Mat4 *local_transform = nullptr,
    bool visible = true,
    const std::vector<uint8_t> *children_type = nullptr,
    const std::vector<::flatbuffers::Offset<void>> *children = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto children_type__ = children_type ? _fbb.CreateVector<uint8_t>(*children_type) : 0;
  auto children__ = children ? _fbb.CreateVector<::flatbuffers::Offset<void>>(*children) : 0;
  return lite::serialization::CreateNodeFB(
      _fbb,
      id,
      name__,
      local_transform,
      visible,
      children_type__,
      children__);
}

struct MeshNodeFB FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MeshNodeFBBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BASE = 4,
    VT_POSITIONS = 6,
    VT_NORMALS = 8,
    VT_UVS = 10,
    VT_INDICES = 12,
    VT_BOUNDS_MIN = 14,
    VT_BOUNDS_MAX = 16,
    VT_MATERIAL_NAME = 18
  };
  const lite::serialization::NodeFB *base() const {
    return GetPointer<const lite::serialization::NodeFB *>(VT_BASE);
  }
  const ::flatbuffers::Vector<const lite::serialization::Vec3 *> *positions() const {
    return GetPointer<const ::flatbuffers::Vector<const lite::serialization::Vec3 *> *>(VT_POSITIONS);
  }
  const ::flatbuffers::Vector<const lite::serialization::Vec3 *> *normals() const {
    return GetPointer<const ::flatbuffers::Vector<const lite::serialization::Vec3 *> *>(VT_NORMALS);
  }
  const ::flatbuffers::Vector<const lite::serialization::Vec2 *> *uvs() const {
    return GetPointer<const ::flatbuffers::Vector<const lite::serialization::Vec2 *> *>(VT_UVS);
  }
  const ::flatbuffers::Vector<uint32_t> *indices() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_INDICES);
  }
  const lite::serialization::Vec3 *bounds_min() const {
    return GetStruct<const lite::serialization::Vec3 *>(VT_BOUNDS_MIN);
  }
  const lite::serialization::Vec3 *bounds_max() const {
    return GetStruct<const lite::serialization::Vec3 *>(VT_BOUNDS_MAX);
  }
  const ::flatbuffers::String *material_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MATERIAL_NAME);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_BASE) &&
           verifier.VerifyTable(base()) &&
           VerifyOffset(verifier, VT_POSITIONS) &&
           verifier.VerifyVector(positions()) &&
           VerifyOffset(verifier, VT_NORMALS) &&
           verifier.VerifyVector(normals()) &&
           VerifyOffset(verifier, VT_UVS) &&
           verifier.VerifyVector(uvs()) &&
           VerifyOffset(verifier, VT_INDICES) &&
           verifier.VerifyVector(indices()) &&
           VerifyField<lite::serialization::Vec3>(verifier, VT_BOUNDS_MIN, 4) &&
           VerifyField<lite::serialization::Vec3>(verifier, VT_BOUNDS_MAX, 4) &&
           VerifyOffset(verifier, VT_MATERIAL_NAME) &&
           verifier.VerifyString(material_name()) &&
           verifier.EndTable();
  }
};

struct MeshNodeFBBuilder {
  typedef MeshNodeFB Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_base(::flatbuffers::Offset<lite::serialization::NodeFB> base) {
    fbb_.AddOffset(MeshNodeFB::VT_BASE, base);
  }
  void add_positions(::flatbuffers::Offset<::flatbuffers::Vector<const lite::serialization::Vec3 *>> positions) {
    fbb_.AddOffset(MeshNodeFB::VT_POSITIONS, positions);
  }
  void add_normals(::flatbuffers::Offset<::flatbuffers::Vector<const lite::serialization::Vec3 *>> normals) {
    fbb_.AddOffset(MeshNodeFB::VT_NORMALS, normals);
  }
  void add_uvs(::flatbuffers::Offset<::flatbuffers::Vector<const lite::serialization::Vec2 *>> uvs) {
    fbb_.AddOffset(MeshNodeFB::VT_UVS, uvs);
  }
  void add_indices(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> indices) {
    fbb_.AddOffset(MeshNodeFB::VT_INDICES, indices);
  }
  void add_bounds_min(const lite::serialization::Vec3 *bounds_min) {
    fbb_.AddStruct(MeshNodeFB::VT_BOUNDS_MIN, bounds_min);
  }
  void add_bounds_max(const lite::serialization::Vec3 *bounds_max) {
    fbb_.AddStruct(MeshNodeFB::VT_BOUNDS_MAX, bounds_max);
  }
  void add_material_name(::flatbuffers::Offset<::flatbuffers::String> material_name) {
    fbb_.AddOffset(MeshNodeFB::VT_MATERIAL_NAME, material_name);
  }
  explicit MeshNodeFBBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MeshNodeFB> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MeshNodeFB>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MeshNodeFB> CreateMeshNodeFB(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<lite::serialization::NodeFB> base = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const lite::serialization::Vec3 *>> positions = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const lite::serialization::Vec3 *>> normals = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const lite::serialization::Vec2 *>> uvs = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> indices = 0,
    const lite::serialization::Vec3 *bounds_min = nullptr,
    const lite::serialization::Vec3 *bounds_max = nullptr,
    ::flatbuffers::Offset<::flatbuffers::String> material_name = 0) {
  MeshNodeFBBuilder builder_(_fbb);
  builder_.add_material_name(material_name);
  builder_.add_bounds_max(bounds_max);
  builder_.add_bounds_min(bounds_min);
  builder_.add_indices(indices);
  builder_.add_uvs(uvs);
  builder_.add_normals(normals);
  builder_.add_positions(positions);
  builder_.add_base(base);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MeshNodeFB> CreateMeshNodeFBDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<lite::serialization::NodeFB> base = 0,
    const std::vector<lite::serialization::Vec3> *positions = nullptr,
    const std::vector<lite::serialization::Vec3> *normals = nullptr,
    const std::vector<lite::serialization::Vec2> *uvs = nullptr,
    const std::vector<uint32_t> *indices = nullptr,
    const lite::serialization::Vec3 *bounds_min = nullptr,
    const lite::serialization::Vec3 *bounds_max = nullptr,
    const char *material_name = nullptr) {
  auto positions__ = positions ? _fbb.CreateVectorOfStructs<lite::serialization::Vec3>(*positions) : 0;
  auto normals__ = normals ? _fbb.CreateVectorOfStructs<lite::serialization::Vec3>(*normals) : 0;
  auto uvs__ = uvs ? _fbb.CreateVectorOfStructs<lite::serialization::Vec2>(*uvs) : 0;
  auto indices__ = indices ? _fbb.CreateVector<uint32_t>(*indices) : 0;
  auto material_name__ = material_name ? _fbb.CreateString(material_name) : 0;
  return lite::serialization::CreateMeshNodeFB(
      _fbb,
      base,
      positions__,
      normals__,
      uvs__,
      indices__,
      bounds_min,
      bounds_max,
      material_name__);
}

struct CameraNodeFB FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CameraNodeFBBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BASE = 4,
    VT_EYE = 6,
    VT_TARGET = 8
  };
  const lite::serialization::NodeFB *base() const {
    return GetPointer<const lite::serialization::NodeFB *>(VT_BASE);
  }
  const lite::serialization::Vec3 *eye() const {
    return GetStruct<const lite::serialization::Vec3 *>(VT_EYE);
  }
  const lite::serialization::Vec3 *target() const {
    return GetStruct<const lite::serialization::Vec3 *>(VT_TARGET);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_BASE) &&
           verifier.VerifyTable(base()) &&
           VerifyField<lite::serialization::Vec3>(verifier, VT_EYE, 4) &&
           VerifyField<lite::serialization::Vec3>(verifier, VT_TARGET, 4) &&
           verifier.EndTable();
  }
};

struct CameraNodeFBBuilder {
  typedef CameraNodeFB Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_base(::flatbuffers::Offset<lite::serialization::NodeFB> base) {
    fbb_.AddOffset(CameraNodeFB::VT_BASE, base);
  }
  void add_eye(const lite::serialization::Vec3 *eye) {
    fbb_.AddStruct(CameraNodeFB::VT_EYE, eye);
  }
  void add_target(const lite::serialization::Vec3 *target) {
    fbb_.AddStruct(CameraNodeFB::VT_TARGET, target);
  }
  explicit CameraNodeFBBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CameraNodeFB> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CameraNodeFB>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CameraNodeFB> CreateCameraNodeFB(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<lite::serialization::NodeFB> base = 0,
    const lite::serialization::Vec3 *eye = nullptr,
    const lite::serialization::Vec3 *target = nullptr) {
  CameraNodeFBBuilder builder_(_fbb);
  builder_.add_target(target);
  builder_.add_eye(eye);
  builder_.add_base(base);
  return builder_.Finish();
}

struct IblFB FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef IblFBBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PATH = 4,
    VT_INTENSITY = 6
  };
  const ::flatbuffers::String *path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PATH);
  }
  float intensity() const {
    return GetField<float>(VT_INTENSITY, 30000.0f);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PATH) &&
           verifier.VerifyString(path()) &&
           VerifyField<float>(verifier, VT_INTENSITY, 4) &&
           verifier.EndTable();
  }
};

struct IblFBBuilder {
  typedef IblFB Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_path(::flatbuffers::Offset<::flatbuffers::String> path) {
    fbb_.AddOffset(IblFB::VT_PATH, path);
  }
  void add_intensity(float intensity) {
    fbb_.AddElement<float>(IblFB::VT_INTENSITY, intensity, 30000.0f);
  }
  explicit IblFBBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<IblFB> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<IblFB>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<IblFB> CreateIblFB(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> path = 0,
    float intensity = 30000.0f) {
  IblFBBuilder builder_(_fbb);
  builder_.add_intensity(intensity);
  builder_.add_path(path);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<IblFB> CreateIblFBDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *path = nullptr,
    float intensity = 30000.0f) {
  auto path__ = path ? _fbb.CreateString(path) : 0;
  return lite::serialization::CreateIblFB(
      _fbb,
      path__,
      intensity);
}

struct SceneFB FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SceneFBBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SCHEMA_VERSION = 4,
    VT_ID = 6,
    VT_IBL = 8,
    VT_MATERIALS_TYPE = 10,
    VT_MATERIALS = 12,
    VT_INSTANCES_TYPE = 14,
    VT_INSTANCES = 16
  };
  uint32_t schema_version() const {
    return GetField<uint32_t>(VT_SCHEMA_VERSION, 1);
  }
  int32_t id() const {
    return GetField<int32_t>(VT_ID, -1);
  }
  const lite::serialization::IblFB *ibl() const {
    return GetPointer<const lite::serialization::IblFB *>(VT_IBL);
  }
  const ::flatbuffers::Vector<uint8_t> *materials_type() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_MATERIALS_TYPE);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *materials() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *>(VT_MATERIALS);
  }
  const ::flatbuffers::Vector<uint8_t> *instances_type() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_INSTANCES_TYPE);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *instances() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *>(VT_INSTANCES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_SCHEMA_VERSION, 4) &&
           VerifyField<int32_t>(verifier, VT_ID, 4) &&
           VerifyOffset(verifier, VT_IBL) &&
           verifier.VerifyTable(ibl()) &&
           VerifyOffset(verifier, VT_MATERIALS_TYPE) &&
           verifier.VerifyVector(materials_type()) &&
           VerifyOffset(verifier, VT_MATERIALS) &&
           verifier.VerifyVector(materials()) &&
           VerifyMaterialKindVector(verifier, materials(), materials_type()) &&
           VerifyOffset(verifier, VT_INSTANCES_TYPE) &&
           verifier.VerifyVector(instances_type()) &&
           VerifyOffset(verifier, VT_INSTANCES) &&
           verifier.VerifyVector(instances()) &&
           VerifyNodeKindVector(verifier, instances(), instances_type()) &&
           verifier.EndTable();
  }
};

struct SceneFBBuilder {
  typedef SceneFB Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_schema_version(uint32_t schema_version) {
    fbb_.AddElement<uint32_t>(SceneFB::VT_SCHEMA_VERSION, schema_version, 1);
  }
  void add_id(int32_t id) {
    fbb_.AddElement<int32_t>(SceneFB::VT_ID, id, -1);
  }
  void add_ibl(::flatbuffers::Offset<lite::serialization::IblFB> ibl) {
    fbb_.AddOffset(SceneFB::VT_IBL, ibl);
  }
  void add_materials_type(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> materials_type) {
    fbb_.AddOffset(SceneFB::VT_MATERIALS_TYPE, materials_type);
  }
  void add_materials(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<void>>> materials) {
    fbb_.AddOffset(SceneFB::VT_MATERIALS, materials);
  }
  void add_instances_type(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> instances_type) {
    fbb_.AddOffset(SceneFB::VT_INSTANCES_TYPE, instances_type);
  }
  void add_instances(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<void>>> instances) {
    fbb_.AddOffset(SceneFB::VT_INSTANCES, instances);
  }
  explicit SceneFBBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SceneFB> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SceneFB>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SceneFB> CreateSceneFB(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t schema_version = 1,
    int32_t id = -1,
    ::flatbuffers::Offset<lite::serialization::IblFB> ibl = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> materials_type = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<void>>> materials = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> instances_type = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<void>>> instances = 0) {
  SceneFBBuilder builder_(_fbb);
  builder_.add_instances(instances);
  builder_.add_instances_type(instances_type);
  builder_.add_materials(materials);
  builder_.add_materials_type(materials_type);
  builder_.add_ibl(ibl);
  builder_.add_id(id);
  builder_.add_schema_version(schema_version);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SceneFB> CreateSceneFBDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t schema_version = 1,
    int32_t id = -1,
    ::flatbuffers::Offset<lite::serialization::IblFB> ibl = 0,
    const std::vector<uint8_t> *materials_type = nullptr,
    const std::vector<::flatbuffers::Offset<void>> *materials = nullptr,
    const std::vector<uint8_t> *instances_type = nullptr,
    const std::vector<::flatbuffers::Offset<void>> *instances = nullptr) {
  auto materials_type__ = materials_type ? _fbb.CreateVector<uint8_t>(*materials_type) : 0;
  auto materials__ = materials ? _fbb.CreateVector<::flatbuffers::Offset<void>>(*materials) : 0;
  auto instances_type__ = instances_type ? _fbb.CreateVector<uint8_t>(*instances_type) : 0;
  auto instances__ = instances ? _fbb.CreateVector<::flatbuffers::Offset<void>>(*instances) : 0;
  return lite::serialization::CreateSceneFB(
      _fbb,
      schema_version,
      id,
      ibl,
      materials_type__,
      materials__,
      instances_type__,
      instances__);
}

template <bool B>
inline bool VerifyMaterialKind(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, MaterialKind type) {
  switch (type) {
    case MaterialKind_NONE: {
      return true;
    }
    case MaterialKind_MaterialFB: {
      auto ptr = reinterpret_cast<const lite::serialization::MaterialFB *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MaterialKind_MPBRLitMaterialFB: {
      auto ptr = reinterpret_cast<const lite::serialization::MPBRLitMaterialFB *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyMaterialKindVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyMaterialKind(
        verifier,  values->Get(i), types->GetEnum<MaterialKind>(i))) {
      return false;
    }
  }
  return true;
}

template <bool B>
inline bool VerifyNodeKind(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, NodeKind type) {
  switch (type) {
    case NodeKind_NONE: {
      return true;
    }
    case NodeKind_NodeFB: {
      auto ptr = reinterpret_cast<const lite::serialization::NodeFB *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case NodeKind_MeshNodeFB: {
      auto ptr = reinterpret_cast<const lite::serialization::MeshNodeFB *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case NodeKind_CameraNodeFB: {
      auto ptr = reinterpret_cast<const lite::serialization::CameraNodeFB *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyNodeKindVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyNodeKind(
        verifier,  values->Get(i), types->GetEnum<NodeKind>(i))) {
      return false;
    }
  }
  return true;
}

inline const lite::serialization::SceneFB *GetSceneFB(const void *buf) {
  return ::flatbuffers::GetRoot<lite::serialization::SceneFB>(buf);
}

inline const lite::serialization::SceneFB *GetSizePrefixedSceneFB(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<lite::serialization::SceneFB>(buf);
}

inline const char *SceneFBIdentifier() {
  return "LSCN";
}

inline bool SceneFBBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, SceneFBIdentifier());
}

inline bool SizePrefixedSceneFBBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, SceneFBIdentifier(), true);
}

template <bool B = false>
inline bool VerifySceneFBBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<lite::serialization::SceneFB>(SceneFBIdentifier());
}

template <bool B = false>
inline bool VerifySizePrefixedSceneFBBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<lite::serialization::SceneFB>(SceneFBIdentifier());
}

inline void FinishSceneFBBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<lite::serialization::SceneFB> root) {
  fbb.Finish(root, SceneFBIdentifier());
}

inline void FinishSizePrefixedSceneFBBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<lite::serialization::SceneFB> root) {
  fbb.FinishSizePrefixed(root, SceneFBIdentifier());
}

}  // namespace serialization
}  // namespace lite

#endif  // FLATBUFFERS_GENERATED_SCENE_LITE_SERIALIZATION_H_
